[
 "¿Eres lo suficientemente valiente como para tomar una foto de un cementerio de medianoche?",
 "Toma una foto del bot, conviértela en tu foto de perfil durante 1 día",
 "VN canta mi globo hay 5",
 "Bebe Coca-Cola hasta que se acabe sin eructar durante 30 segundos",
 "Come 1 Chili sin beber, sin freír por 2 minutos",
 "Sumerge tu celular en agua por 30 segundos",
 "VN *Te amo*",
 "Corte de ganso de pato cantor (VN)",
 "Envíale un mensaje a tu ex y dile _todavía me gustas_",
 "Llamar a la enamorada/novia ahora y enviar un mensaje de texto al jugador",
 "Papá a un miembro del grupo",
 "Papá lo que tienes delante",
 "SS llamada reciente whatsapp",
 "Envía una nota de voz diciendo ¿puedo llamarte bebé?",
 "Usar la foto de Sule durante 3 días",
 "Escriba en el idioma local las 24 horas",
 "Cambiar nombre a _gue lucinta luna_ por 5 horas",
 "Chatea para contactar a wa en el orden de acuerdo a tu %batre, luego dile _tengo suerte de tenerte_",
 "Habla de broma con tu ex y di *te amo, por favor vuelve*",
 "Grabar voz leer sura al-kautsar",
 "Cambiar nombre a *BOWO* por 24 horas",
 "¡Nombra tu tipo de novio!",
 "VN *Te amo*",
 "¡Tienes que papilla ahora!",
 "Debes dividir el límite, al menos 2 por usuario",
 "El chat de 1 hora debe ser 4l4Y 8AN93T"
 ]
